const mockProducts = [
  {
    id: 1,
    category: 'Lipstick',
    name: 'Velvet Rose Matte Lipstick',
    description: 'Weightless velvet-matte lipstick infused with hyaluronic acid and organic rosehip oil for 12-hour comfortable hydration and high-pigment payoff.',
    price: 499.00,
    shade: 'Velvet Rose',
    stock: 45,
    image: 'assets/products/lipstick_rose.jpg',
    images: [
      'assets/products/lipstick_rose.jpg',
      'assets/products/lipstick_crimson.jpg',
      'assets/products/lipliner_mauve.jpg',
      'assets/products/blush_peony.jpg'
    ],
    brand: 'ZYRA',
    color: 'Rose Pink',
    finish: 'Matte',
    skin_type: 'All Skin Types',
    rating: 4.9,
    reviews_count: 128,
    ingredients: 'Dimethicone, Rosa Canina (Rosehip) Fruit Oil, Hyaluronic Acid, Tocopheryl Acetate.',
    benefits: '12-Hour Hydrating Hold, Non-Drying Silk Cushion, 100% Vegan & Cruelty-Free.',
    how_to_use: 'Apply directly from bullet starting at center of lips.',
    is_featured: 1,
    is_bestseller: 1,
    is_new: 0
  },
  {
    id: 2,
    category: 'Lipstick',
    name: 'Satin Crimson Nude Lipstick',
    description: 'Luminous satin finish lipstick that wraps lips in ultra-rich pigmentation, silky feel, and understated luxury sheen.',
    price: 449.00,
    shade: 'Crimson Nude',
    stock: 30,
    image: 'assets/products/lipstick_crimson.jpg',
    images: [
      'assets/products/lipstick_crimson.jpg',
      'assets/products/lipstick_rose.jpg',
      'assets/products/lipgloss_crystal.jpg',
      'assets/products/lipliner_mauve.jpg'
    ],
    brand: 'ZYRA',
    color: 'Crimson Red',
    finish: 'Satin',
    skin_type: 'All Skin Types',
    rating: 4.8,
    reviews_count: 86,
    ingredients: 'Ricinus Communis (Castor) Seed Oil, Simmondsia Chinensis (Jojoba) Oil, Euphorbia Cerifera Wax.',
    benefits: 'Luminous Satin Sheen, Nourishing Jojoba Base, Smooth Glide.',
    how_to_use: 'Glide across clean lips. Layer for buildable intensity.',
    is_featured: 0,
    is_bestseller: 1,
    is_new: 1
  },
  {
    id: 3,
    category: 'Foundation',
    name: 'Luminous Silk Hydrating Foundation',
    description: 'Ultra-fluid liquid foundation providing buildable medium-to-full coverage with a natural lit-from-within radiant glow.',
    price: 899.00,
    shade: 'Warm Honey',
    stock: 60,
    image: 'assets/products/foundation_silk.jpg',
    images: [
      'assets/products/foundation_silk.jpg',
      'assets/products/foundation_matte.jpg',
      'assets/products/concealer_peach.jpg',
      'assets/products/compact_gold.jpg'
    ],
    brand: 'ZYRA',
    color: 'Warm Beige',
    finish: 'Dewy',
    skin_type: 'Dry & Normal',
    rating: 4.9,
    reviews_count: 210,
    ingredients: 'Aqua, Cyclopentasiloxane, Glycerin, Niacinamide (5%), Squalane, Titanium Dioxide.',
    benefits: '24-Hour Hydration Veil, Niacinamide Brightening Complex.',
    how_to_use: 'Dispense 1-2 pumps and blend outward with beauty sponge.',
    is_featured: 1,
    is_bestseller: 1,
    is_new: 0
  },
  {
    id: 4,
    category: 'Foundation',
    name: 'Soft Matte Perfecting Foundation',
    description: 'Oil-free velvet matte foundation formulated with micronized silica and salicylic acid for all-day poreless coverage.',
    price: 799.00,
    shade: 'Porcelain Ivory',
    stock: 40,
    image: 'assets/products/foundation_matte.jpg',
    images: [
      'assets/products/foundation_matte.jpg',
      'assets/products/foundation_silk.jpg',
      'assets/products/compact_gold.jpg',
      'assets/products/primer_glow.jpg'
    ],
    brand: 'ZYRA',
    color: 'Ivory Nude',
    finish: 'Matte',
    skin_type: 'Oily & Combination',
    rating: 4.7,
    reviews_count: 142,
    ingredients: 'Aqua, Silica, Zinc Oxide, Salicylic Acid (1%), Green Tea Leaf Extract.',
    benefits: 'Sebum Absorbing Micro-Spheres, Transfer-Proof 16H Hold.',
    how_to_use: 'Apply onto prepped skin with foundation brush.',
    is_featured: 0,
    is_bestseller: 0,
    is_new: 1
  },
  {
    id: 5,
    category: 'Concealer',
    name: 'Radiant Skin Full Coverage Concealer',
    description: 'Creamy crease-proof concealer that instantly blurs dark circles, redness, and blemishes with a soothing botanical finish.',
    price: 399.00,
    shade: 'Light Peach',
    stock: 50,
    image: 'assets/products/concealer_peach.jpg',
    images: [
      'assets/products/concealer_peach.jpg',
      'assets/products/foundation_silk.jpg',
      'assets/products/compact_gold.jpg',
      'assets/products/highlighter_champagne.jpg'
    ],
    brand: 'ZYRA',
    color: 'Peach Warm',
    finish: 'Satin',
    skin_type: 'All Skin Types',
    rating: 4.8,
    reviews_count: 94,
    ingredients: 'Aqua, Glycerin, Caprylic Triglyceride, Coffee Seed Extract, Caffeine.',
    benefits: 'De-Puffing Coffee Complex, Waterproof & Crease-Proof.',
    how_to_use: 'Dot under eyes or over spots and tap into skin.',
    is_featured: 1,
    is_bestseller: 0,
    is_new: 0
  },
  {
    id: 6,
    category: 'Compact Powder',
    name: 'Aura Micro-Fine Pressed Powder',
    description: 'Weightless translucent setting compact powder that diffuses light, sets makeup, and absorbs shine for 16 hours.',
    price: 499.00,
    shade: 'Translucent Gold',
    stock: 35,
    image: 'assets/products/compact_gold.jpg',
    images: [
      'assets/products/compact_gold.jpg',
      'assets/products/foundation_matte.jpg',
      'assets/products/highlighter_champagne.jpg',
      'assets/products/blush_peony.jpg'
    ],
    brand: 'ZYRA',
    color: 'Champagne Gold',
    finish: 'Matte',
    skin_type: 'All Skin Types',
    rating: 4.9,
    reviews_count: 78,
    ingredients: 'Talc Free Mica, Silica, Zinc Stearate, Argan Kernel Oil.',
    benefits: 'Zero Flashback, Ultra-Fine Micro-Milled Minerals.',
    how_to_use: 'Press gently into skin using enclosed luxury puff.',
    is_featured: 0,
    is_bestseller: 1,
    is_new: 0
  },
  {
    id: 7,
    category: 'Blush',
    name: 'Soft Petal Liquid Blush',
    description: 'Liquid cream blush that melts effortlessly into skin, delivering a fresh flush of youth-building radiance.',
    price: 399.00,
    shade: 'Soft Peony',
    stock: 55,
    image: 'assets/products/blush_peony.jpg',
    images: [
      'assets/products/blush_peony.jpg',
      'assets/products/lipstick_rose.jpg',
      'assets/products/highlighter_champagne.jpg',
      'assets/products/lipgloss_crystal.jpg'
    ],
    brand: 'ZYRA',
    color: 'Peony Pink',
    finish: 'Dewy',
    skin_type: 'All Skin Types',
    rating: 4.9,
    reviews_count: 165,
    ingredients: 'Isododecane, Squalane, Camellia Sinensis Leaf Extract, Rose Water.',
    benefits: 'Weightless Liquid Flush, Hydrating Rose Hydrosol Base.',
    how_to_use: 'Dab 1-2 dots onto cheek apples and blend upward.',
    is_featured: 1,
    is_bestseller: 1,
    is_new: 1
  },
  {
    id: 8,
    category: 'Primer',
    name: 'Silk Veil Poreless Radiant Primer',
    description: 'Smoothing hydrating primer infused with pearl essence and hyaluronic acid to create a silky canvas for makeup.',
    price: 599.00,
    shade: 'Clear Glow',
    stock: 40,
    image: 'assets/products/primer_glow.jpg',
    images: [
      'assets/products/primer_glow.jpg',
      'assets/products/foundation_silk.jpg',
      'assets/products/settingspray_dewy.jpg',
      'assets/products/serum_elixir.jpg'
    ],
    brand: 'ZYRA',
    color: 'Clear Pearl',
    finish: 'Dewy',
    skin_type: 'All Skin Types',
    rating: 4.8,
    reviews_count: 112,
    ingredients: 'Dimethicone Crosspolymer, Camellia Extract, Sodium Hyaluronate.',
    benefits: 'Pore-Filling Velvet Texture, Prolongs Makeup Wear.',
    how_to_use: 'Smooth pea-sized amount over clean moisturized skin.',
    is_featured: 0,
    is_bestseller: 0,
    is_new: 1
  },
  {
    id: 9,
    category: 'Highlighter',
    name: 'Celestial Glow Liquid Highlighter',
    description: 'Concentrated liquid illuminator packed with pearl pigments for buildable glass-skin luminosity.',
    price: 499.00,
    shade: 'Champagne Shimmer',
    stock: 45,
    image: 'assets/products/highlighter_champagne.jpg',
    images: [
      'assets/products/highlighter_champagne.jpg',
      'assets/products/blush_peony.jpg',
      'assets/products/compact_gold.jpg',
      'assets/products/eyeshadow_palette.jpg'
    ],
    brand: 'ZYRA',
    color: 'Champagne Gold',
    finish: 'Shimmer',
    skin_type: 'All Skin Types',
    rating: 4.9,
    reviews_count: 184,
    ingredients: 'Mica, Titanium Dioxide, Synthetic Fluorphlogopite, Squalane.',
    benefits: 'Glass-Skin Shimmer, Multi-Use for Cheekbones & Collarbones.',
    how_to_use: 'Apply to high points of face (cheekbones, brow bone).',
    is_featured: 1,
    is_bestseller: 1,
    is_new: 0
  },
  {
    id: 10,
    category: 'Mascara',
    name: 'Lash Sculpt Volume & Curl Mascara',
    description: 'Smudge-proof 24-hour lengthening mascara with an hourglass wand that lifts and fans every single lash.',
    price: 349.00,
    shade: 'Midnight Black',
    stock: 70,
    image: 'assets/products/mascara_black.jpg',
    images: [
      'assets/products/mascara_black.jpg',
      'assets/products/eyeliner_black.jpg',
      'assets/products/kajal_carbon.jpg',
      'assets/products/eyeshadow_palette.jpg'
    ],
    brand: 'ZYRA',
    color: 'Deep Black',
    finish: 'Glossy',
    skin_type: 'Sensitive Eyes',
    rating: 4.8,
    reviews_count: 195,
    ingredients: 'Carnauba Wax, Acacia Senegal Gum, Panthenol (Pro-Vitamin B5).',
    benefits: '300% Volume Boost, Zero Flaking.',
    how_to_use: 'Wiggle wand from root to tip of lashes.',
    is_featured: 1,
    is_bestseller: 1,
    is_new: 0
  },
  {
    id: 11,
    category: 'Eyeliner',
    name: 'Precision Waterproof Liquid Eyeliner',
    description: 'Ultra-fine 0.1mm felt-tip pen for razor-sharp winged liner with waterproof carbon black intensity.',
    price: 299.00,
    shade: 'Jet Black',
    stock: 80,
    image: 'assets/products/eyeliner_black.jpg',
    images: [
      'assets/products/eyeliner_black.jpg',
      'assets/products/mascara_black.jpg',
      'assets/products/kajal_carbon.jpg',
      'assets/products/eyeshadow_palette.jpg'
    ],
    brand: 'ZYRA',
    color: 'Jet Black',
    finish: 'Matte',
    skin_type: 'All Skin Types',
    rating: 4.7,
    reviews_count: 130,
    ingredients: 'Water, Acrylates Copolymer, Carbon Black, Organic Chamomile Extract.',
    benefits: '24-Hour Waterproof & Sweatproof, Micro-Precision Tip.',
    how_to_use: 'Draw along upper lash line extending out to a wing.',
    is_featured: 0,
    is_bestseller: 0,
    is_new: 1
  },
  {
    id: 12,
    category: 'Kajal',
    name: 'Intense Kohl Gel Kajal',
    description: 'Creamy botanical kajal pencil enriched with Sweet Almond Oil and Vitamin E for smudgeless 16-hour waterline wear.',
    price: 249.00,
    shade: 'Deep Carbon',
    stock: 65,
    image: 'assets/products/kajal_carbon.jpg',
    images: [
      'assets/products/kajal_carbon.jpg',
      'assets/products/eyeliner_black.jpg',
      'assets/products/mascara_black.jpg',
      'assets/products/eyeshadow_palette.jpg'
    ],
    brand: 'ZYRA',
    color: 'Carbon Black',
    finish: 'Matte',
    skin_type: 'Sensitive Eyes',
    rating: 4.8,
    reviews_count: 150,
    ingredients: 'Prunus Amygdalus Dulcis Oil, Tocopherol (Vitamin E), Carbon Pigment.',
    benefits: 'Ophthalmologist Tested, Safe for Contact Lens Wearers.',
    how_to_use: 'Glide smoothly along lower and upper waterline.',
    is_featured: 0,
    is_bestseller: 1,
    is_new: 0
  },
  {
    id: 13,
    category: 'Eyeshadow',
    name: 'Rose Gold Luxury Eyeshadow Palette',
    description: '12 high-pigment shades featuring buttery mattes, sparkling foils, and silky shimmers tailored for all skin tones.',
    price: 899.00,
    shade: '12-Shade Palette',
    stock: 30,
    image: 'assets/products/eyeshadow_palette.jpg',
    images: [
      'assets/products/eyeshadow_palette.jpg',
      'assets/products/highlighter_champagne.jpg',
      'assets/products/mascara_black.jpg',
      'assets/products/brushes_set.jpg'
    ],
    brand: 'ZYRA',
    color: 'Rose Gold Metallic',
    finish: 'Shimmer & Matte',
    skin_type: 'All Skin Types',
    rating: 5.0,
    reviews_count: 310,
    ingredients: 'Mica, Talc Free Silicates, Magnesium Stearate, Tocopheryl Acetate.',
    benefits: 'Zero Fallout, High Color Payoff, Built-In Mirror.',
    how_to_use: 'Sweep neutral mattes across lid as base, press shimmer foil onto center.',
    is_featured: 1,
    is_bestseller: 1,
    is_new: 1
  },
  {
    id: 14,
    category: 'Lip Gloss',
    name: 'Glass Shine Plumping Lip Gloss',
    description: 'Non-sticky high-shine gloss infused with natural peptide complexes and coconut nectar for instantly fuller-looking lips.',
    price: 349.00,
    shade: 'Crystal Rose',
    stock: 50,
    image: 'assets/products/lipgloss_crystal.jpg',
    images: [
      'assets/products/lipgloss_crystal.jpg',
      'assets/products/lipstick_rose.jpg',
      'assets/products/lipliner_mauve.jpg',
      'assets/products/blush_peony.jpg'
    ],
    brand: 'ZYRA',
    color: 'Crystal Pink',
    finish: 'Glossy',
    skin_type: 'All Skin Types',
    rating: 4.9,
    reviews_count: 140,
    ingredients: 'Polybutene, Cocos Nucifera (Coconut) Oil, Palmitoyl Tripeptide-1.',
    benefits: 'Instant Cooling Plumping Action, 3D Glass Mirror Shine.',
    how_to_use: 'Apply directly onto bare lips or layer over ZYRA lipstick.',
    is_featured: 1,
    is_bestseller: 0,
    is_new: 1
  },
  {
    id: 15,
    category: 'Lip Liner',
    name: 'Sculpt & Define Precision Lip Pencil',
    description: 'Creamy waterproof lip liner pencil that prevents feathering and creates defined, voluptuous contours.',
    price: 299.00,
    shade: 'Mauve Nude',
    stock: 40,
    image: 'assets/products/lipliner_mauve.jpg',
    images: [
      'assets/products/lipliner_mauve.jpg',
      'assets/products/lipstick_rose.jpg',
      'assets/products/lipstick_crimson.jpg',
      'assets/products/lipgloss_crystal.jpg'
    ],
    brand: 'ZYRA',
    color: 'Nude Mauve',
    finish: 'Matte',
    skin_type: 'All Skin Types',
    rating: 4.7,
    reviews_count: 75,
    ingredients: 'Simmondsia Chinensis (Jojoba) Seed Oil, Carnauba Wax, Synthetic Wax.',
    benefits: 'Waterproof 12H Contour, Smooth Drag-Free Application.',
    how_to_use: 'Outline outer lip border starting at Cupid’s bow.',
    is_featured: 0,
    is_bestseller: 0,
    is_new: 0
  },
  {
    id: 16,
    category: 'Setting Spray',
    name: 'Everlasting Dewy Setting Mist',
    description: 'Micro-fine setting spray that seals makeup for up to 18 hours while locking in skin hydration with aloe and niacinamide.',
    price: 499.00,
    shade: 'Dewy Clear',
    stock: 45,
    image: 'assets/products/settingspray_dewy.jpg',
    images: [
      'assets/products/settingspray_dewy.jpg',
      'assets/products/primer_glow.jpg',
      'assets/products/foundation_silk.jpg',
      'assets/products/cream_rose.jpg'
    ],
    brand: 'ZYRA',
    color: 'Clear Mist',
    finish: 'Dewy',
    skin_type: 'All Skin Types',
    rating: 4.8,
    reviews_count: 98,
    ingredients: 'Aqua, Aloe Barbadensis Leaf Juice, Niacinamide, Rose Hydrosol.',
    benefits: '18-Hour Makeup Lock, Ultra-Fine Aerosol-Free Pump.',
    how_to_use: 'Hold bottle 8-10 inches away and mist in X and T shape.',
    is_featured: 0,
    is_bestseller: 1,
    is_new: 0
  },
  {
    id: 17,
    category: 'Makeup Brushes',
    name: 'Velvet Touch 8-Piece Luxury Brush Set',
    description: 'Ultra-soft cruelty-free synthetic fiber brushes with ergonomic Rose Gold metallic handles and faux leather travel case.',
    price: 999.00,
    shade: 'Rose Gold Edition',
    stock: 25,
    image: 'assets/products/brushes_set.jpg',
    images: [
      'assets/products/brushes_set.jpg',
      'assets/products/sponge_pink.jpg',
      'assets/products/eyeshadow_palette.jpg',
      'assets/products/compact_gold.jpg'
    ],
    brand: 'ZYRA',
    color: 'Rose Gold',
    finish: 'Luxury Taklon',
    skin_type: 'All Skin Types',
    rating: 4.9,
    reviews_count: 120,
    ingredients: 'Taklon Synthetic Bristles, Recycled Aluminum Ferrule.',
    benefits: 'Dermatologist Safe, Zero Shedding Guarantee.',
    how_to_use: 'Use dense brushes for liquids and fluffy brushes for powders.',
    is_featured: 1,
    is_bestseller: 1,
    is_new: 0
  },
  {
    id: 18,
    category: 'Beauty Blender',
    name: 'Seamless Blend Miracle Sponge Duo',
    description: 'Precision teardrop beauty sponges for streak-free liquid foundation and concealer application wet or dry.',
    price: 299.00,
    shade: 'Blush Pink',
    stock: 90,
    image: 'assets/products/sponge_pink.jpg',
    images: [
      'assets/products/sponge_pink.jpg',
      'assets/products/brushes_set.jpg',
      'assets/products/foundation_silk.jpg',
      'assets/products/concealer_peach.jpg'
    ],
    brand: 'ZYRA',
    color: 'Blush Pink',
    finish: 'Airbrush',
    skin_type: 'All Skin Types',
    rating: 4.8,
    reviews_count: 205,
    ingredients: 'Hydrophilic Polyurethane Foam (100% Latex-Free).',
    benefits: 'Expands 50% When Wet, Zero Product Waste.',
    how_to_use: 'Wet thoroughly with water and squeeze excess. Bounce on face.',
    is_featured: 0,
    is_bestseller: 1,
    is_new: 1
  },
  {
    id: 19,
    category: 'Skincare',
    name: 'Botanical Youth Elixir Facial Serum',
    description: 'Restorative facial oil serum formulated with Bakuchiol (Natural Retinol Alternative), Rosehip Oil, and Squalane for ageless glow.',
    price: 799.00,
    shade: 'Golden Elixir',
    stock: 35,
    image: 'assets/products/serum_elixir.jpg',
    images: [
      'assets/products/serum_elixir.jpg',
      'assets/products/cream_rose.jpg',
      'assets/products/primer_glow.jpg',
      'assets/products/highlighter_champagne.jpg'
    ],
    brand: 'ZYRA',
    color: 'Golden Glow',
    finish: 'Dewy',
    skin_type: 'All Skin Types',
    rating: 4.9,
    reviews_count: 175,
    ingredients: 'Squalane, Bakuchiol (1%), Rosa Rubiginosa (Rosehip) Seed Oil.',
    benefits: 'Smooths Fine Lines, Deep Lipid Barrier Nourishment.',
    how_to_use: 'Warm 3-4 drops between palms and press onto face and neck.',
    is_featured: 1,
    is_bestseller: 1,
    is_new: 1
  },
  {
    id: 20,
    category: 'Skincare',
    name: 'Hydra-Rose Moisture Surge Cream',
    description: 'Rich velvety moisturizer packed with Damask Rose water, Ceramide NP, and triple molecular weight Hyaluronic Acid.',
    price: 699.00,
    shade: 'Soft Ivory Cream',
    stock: 40,
    image: 'assets/products/cream_rose.jpg',
    images: [
      'assets/products/cream_rose.jpg',
      'assets/products/serum_elixir.jpg',
      'assets/products/primer_glow.jpg',
      'assets/products/settingspray_dewy.jpg'
    ],
    brand: 'ZYRA',
    color: 'Soft Pink Cream',
    finish: 'Dewy',
    skin_type: 'Dry & Normal',
    rating: 4.9,
    reviews_count: 134,
    ingredients: 'Rosa Damascena Flower Water, Sodium Hyaluronate, Ceramide NP.',
    benefits: '72-Hour Plumping Hydration, Strengthens Moisture Barrier.',
    how_to_use: 'Massage dime-sized amount onto face after serum.',
    is_featured: 0,
    is_bestseller: 1,
    is_new: 0
  },
  {
    id: 21,
    category: 'Lipstick',
    name: 'Berry Divine Creamy Lipstick',
    description: 'Nourishing berry red creamy lipstick packed with jojoba butter and vitamin E for soft supple lips.',
    price: 399.00,
    shade: 'Berry Red',
    stock: 50,
    image: 'assets/products/lipstick_rose.jpg',
    images: [
      'assets/products/lipstick_rose.jpg',
      'assets/products/lipstick_crimson.jpg',
      'assets/products/lipliner_mauve.jpg'
    ],
    brand: 'ZYRA',
    color: 'Berry',
    finish: 'Creamy',
    skin_type: 'All Skin Types',
    rating: 4.7,
    reviews_count: 64,
    ingredients: 'Jojoba Butter, Tocopheryl Acetate, Mineral Pigments.',
    benefits: 'Instant Hydration, Vivid Color Payoff.',
    how_to_use: 'Glide across lips for vibrant berry tone.',
    is_featured: 0,
    is_bestseller: 0,
    is_new: 1
  },
  {
    id: 22,
    category: 'Lip Gloss',
    name: 'Tinted Nude Hydrating Lip Oil',
    description: 'Lightweight lip oil infused with sweet almond oil and rosehip extract for non-sticky sheer color.',
    price: 299.00,
    shade: 'Honey Nude',
    stock: 60,
    image: 'assets/products/lipgloss_crystal.jpg',
    images: [
      'assets/products/lipgloss_crystal.jpg',
      'assets/products/lipstick_rose.jpg',
      'assets/products/blush_peony.jpg'
    ],
    brand: 'ZYRA',
    color: 'Honey Nude',
    finish: 'Glossy',
    skin_type: 'All Skin Types',
    rating: 4.8,
    reviews_count: 82,
    ingredients: 'Almond Oil, Rosehip Extract, Vitamin E.',
    benefits: 'Deep Nourishment, Cushion Soft Sheen.',
    how_to_use: 'Apply directly onto bare lips.',
    is_featured: 0,
    is_bestseller: 1,
    is_new: 1
  },
  {
    id: 23,
    category: 'Lip Liner',
    name: 'Velvet Matte Waterproof Lip Pencil',
    description: 'Precision glide lip pencil that defines lips with smooth smudge-free color hold.',
    price: 249.00,
    shade: 'Rosewood',
    stock: 45,
    image: 'assets/products/lipliner_mauve.jpg',
    images: [
      'assets/products/lipliner_mauve.jpg',
      'assets/products/lipstick_rose.jpg',
      'assets/products/lipstick_crimson.jpg'
    ],
    brand: 'ZYRA',
    color: 'Rosewood',
    finish: 'Matte',
    skin_type: 'All Skin Types',
    rating: 4.6,
    reviews_count: 55,
    ingredients: 'Carnauba Wax, Synthetic Wax, Castor Oil.',
    benefits: 'Waterproof Hold, Prevents Bleeding.',
    how_to_use: 'Trace natural lip line before lipstick.',
    is_featured: 0,
    is_bestseller: 0,
    is_new: 0
  },
  {
    id: 24,
    category: 'Blush',
    name: 'Velvet Cheek & Lip Flush Tint',
    description: 'Multi-use cream tint for cheeks and lips that blends effortlessly into a healthy flush.',
    price: 349.00,
    shade: 'Coral Bloom',
    stock: 40,
    image: 'assets/products/blush_peony.jpg',
    images: [
      'assets/products/blush_peony.jpg',
      'assets/products/highlighter_champagne.jpg',
      'assets/products/lipstick_rose.jpg'
    ],
    brand: 'ZYRA',
    color: 'Coral',
    finish: 'Natural Satin',
    skin_type: 'All Skin Types',
    rating: 4.8,
    reviews_count: 91,
    ingredients: 'Shea Butter, Camellia Extract, Mineral Pigments.',
    benefits: '2-in-1 Cheek & Lip Flush, Lightweight.',
    how_to_use: 'Dab on cheeks or lips with fingertips.',
    is_featured: 0,
    is_bestseller: 1,
    is_new: 1
  },
  {
    id: 25,
    category: 'Setting Spray',
    name: 'Matte Fix 12H Oil Control Spray',
    description: 'Refreshing mist that absorbs extra oil and locks in makeup for a velvety shine-free finish.',
    price: 399.00,
    shade: 'Matte Clear',
    stock: 35,
    image: 'assets/products/settingspray_dewy.jpg',
    images: [
      'assets/products/settingspray_dewy.jpg',
      'assets/products/foundation_matte.jpg',
      'assets/products/primer_glow.jpg'
    ],
    brand: 'ZYRA',
    color: 'Clear',
    finish: 'Matte',
    skin_type: 'Oily & Combination',
    rating: 4.7,
    reviews_count: 73,
    ingredients: 'Niacinamide, Witch Hazel Extract, Green Tea.',
    benefits: 'Shine-Control, Long Lasting Hold.',
    how_to_use: 'Spray 8 inches away from face after makeup.',
    is_featured: 0,
    is_bestseller: 0,
    is_new: 0
  },
  {
    id: 26,
    category: 'Kajal',
    name: 'Smudge-Proof Brown Gel Kajal',
    description: 'Deep chocolate brown kajal pencil for a soft romantic eye contour that lasts all day.',
    price: 249.00,
    shade: 'Rich Brown',
    stock: 55,
    image: 'assets/products/kajal_carbon.jpg',
    images: [
      'assets/products/kajal_carbon.jpg',
      'assets/products/eyeliner_black.jpg',
      'assets/products/eyeshadow_palette.jpg'
    ],
    brand: 'ZYRA',
    color: 'Brown',
    finish: 'Matte',
    skin_type: 'Sensitive Eyes',
    rating: 4.8,
    reviews_count: 88,
    ingredients: 'Almond Oil, Vitamin E, Iron Oxide Brown.',
    benefits: 'Soft Smokey Look, 16H Wear.',
    how_to_use: 'Glide on lower waterline.',
    is_featured: 0,
    is_bestseller: 1,
    is_new: 1
  },
  {
    id: 27,
    category: 'Skincare',
    name: 'Rosewater Glow Hydrating Face Mist',
    description: '100% pure steam-distilled Damask Rose water mist that calms skin and restores natural dewiness.',
    price: 299.00,
    shade: 'Pure Rose',
    stock: 75,
    image: 'assets/products/cream_rose.jpg',
    images: [
      'assets/products/cream_rose.jpg',
      'assets/products/serum_elixir.jpg',
      'assets/products/settingspray_dewy.jpg'
    ],
    brand: 'ZYRA',
    color: 'Rose',
    finish: 'Dewy',
    skin_type: 'All Skin Types',
    rating: 4.9,
    reviews_count: 145,
    ingredients: '100% Organic Damask Rose Hydrosol.',
    benefits: 'Instant Soothing Hydration, Natural Glow.',
    how_to_use: 'Mist face throughout the day to refresh.',
    is_featured: 1,
    is_bestseller: 1,
    is_new: 0
  },
  {
    id: 28,
    category: 'Beauty Blender',
    name: 'Micro Mini Contour Sponge Trio',
    description: 'Mini teardrop precision sponges designed for under-eye concealer and nose contouring.',
    price: 249.00,
    shade: 'Rose & Peach',
    stock: 80,
    image: 'assets/products/sponge_pink.jpg',
    images: [
      'assets/products/sponge_pink.jpg',
      'assets/products/concealer_peach.jpg',
      'assets/products/brushes_set.jpg'
    ],
    brand: 'ZYRA',
    color: 'Pink & Peach',
    finish: 'Seamless',
    skin_type: 'All Skin Types',
    rating: 4.7,
    reviews_count: 96,
    ingredients: 'Latex-Free Hydrophilic Sponge Foam.',
    benefits: 'Precision Target Blending.',
    how_to_use: 'Dampen and tap under eyes.',
    is_featured: 0,
    is_bestseller: 0,
    is_new: 1
  },
  {
    id: 29,
    category: 'Eyeshadow',
    name: 'Pocket Quad Shimmer Eyeshadow',
    description: 'Portable 4-shade eyeshadow quad featuring everyday warm nude mattes and champagne shimmers.',
    price: 399.00,
    shade: 'Warm Sunset Quad',
    stock: 45,
    image: 'assets/products/eyeshadow_palette.jpg',
    images: [
      'assets/products/eyeshadow_palette.jpg',
      'assets/products/highlighter_champagne.jpg',
      'assets/products/compact_gold.jpg'
    ],
    brand: 'ZYRA',
    color: 'Warm Nude Shimmer',
    finish: 'Shimmer & Matte',
    skin_type: 'All Skin Types',
    rating: 4.8,
    reviews_count: 110,
    ingredients: 'Mica, Titanium Dioxide, Magnesium Stearate.',
    benefits: 'Travel-Friendly, High Pigment Payoff.',
    how_to_use: 'Apply quad shades from light to dark.',
    is_featured: 0,
    is_bestseller: 1,
    is_new: 0
  },
  {
    id: 30,
    category: 'Makeup Brushes',
    name: 'Precision Angled Eyeliner & Brow Brush',
    description: 'Ultra-thin angled synthetic bristle brush for sharp eyeliner wing and eyebrow fill.',
    price: 199.00,
    shade: 'Rose Gold Metallic',
    stock: 100,
    image: 'assets/products/brushes_set.jpg',
    images: [
      'assets/products/brushes_set.jpg',
      'assets/products/eyeliner_black.jpg',
      'assets/products/kajal_carbon.jpg'
    ],
    brand: 'ZYRA',
    color: 'Rose Gold',
    finish: 'Precision Synthetic',
    skin_type: 'All Skin Types',
    rating: 4.8,
    reviews_count: 130,
    ingredients: 'Taklon Synthetic Bristles, Brass Ferrule.',
    benefits: 'Razor Sharp Precision Lines.',
    how_to_use: 'Dip in gel liner or brow pomade.',
    is_featured: 0,
    is_bestseller: 0,
    is_new: 1
  }
];

module.exports = mockProducts;
